name: Feature Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Perform Linter Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.22"

      - name: Install Dependencies
        run: go mod download

      - name: Run GolangCI-Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v6.0.1
